server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://34.84.105.154:3306/wancs?characterEncoding=utf8
    username: root
    password: wancs@001
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: kr.co.fastcampus.eatgo
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true